server:
  port: 8081

#Prod
bot:
  name: avto_Inspector_bot
  token: 6518433545:AAEPpXf6v3kntj2Yfp9SW4OAQG4a93pgVgs
  admin-chatId: 5636109529
  admin-link: https://t.me/LPR_Inspectors

logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
    root: info
  file:
    path: './var/log'
    name: ${logging.file.path}/bot.log
