server:
  port: 8081

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  admin-chatId: ${BOT_ADMIN_CHATID}
  admin-link: ${BOT_ADMIN_LINK}

logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
    root: info
  file:
    path: './var/log'
    name: ${logging.file.path}/bot.log
